services:
    toxyy.anonymousposts.listener:
        class: toxyy\anonymousposts\event\listener
        arguments:
            - '@language'
            - '@template'
            - '@auth'
            - '@request'
            - '@toxyy.anonymousposts.helper'
        tags:
            - { name: event.listener }
    toxyy.anonymousposts.helper:
        class: toxyy\anonymousposts\core\helper
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@auth'
