services:
    toxyy.anonymousposts.listener:
        class: toxyy\anonymousposts\event\listener
        arguments:
            - '@language'
            - '@template'
            - '@user'
            - '@auth'
            - '@request'
            - '@notification_manager'
            - '@toxyy.anonymousposts.driver'
        tags:
            - { name: event.listener }
    toxyy.anonymousposts.driver:
        class: toxyy\anonymousposts\core\driver
        arguments:
            - '@dbal.conn'
